### ISSUE TITLE
Error: Array specification required in ALLOCATE statement at (1)

### ISSUE THREAD

**Issue by jaykumar16** [cmbant/CosmoMC#10]
I am using ifort version 18

and I am still getting this menage;
ObjectLists.f90:501:17:

         allocate(this%Items, source = TmpItems)
                 1
Error: Array specification required in ALLOCATE statement at (1)
ObjectLists.f90:328:21:

             allocate(Pt%P, source= P)
                     1
Error: Array specification required in ALLOCATE statement at (1)

**Comment by cmbant** [comment]
This sounds like a compiler bug, though I can't reproduce it with version 18 on Windows. Which version exactly/check if there are any minor updates?

**Comment by jaykumar16** [comment]
I am trying to install in Linux mint 18.2 using ifort but when I use ifort I am still getting error.

**Comment by cmbant** [comment]
Are you sure it's not using gfortran? The error sounds like a version of gfortran earlier than 6.

**Comment by jaykumar16** [comment]
This is my Makefile. 
MPIF90C ?= mpif90
fortErr = $(shell which ifort >/dev/null; echo $$?)

#these settings for ifort 14 and higher. Earlier versions will not work.
ifeq "$(ifortErr)" "0"
#ifort; Can remove -xHost if your cluster is not uniform, or specify specific processor optimizations -x...

F90C     =ifort
#use this if mpif90 is trying to use gfortran: MPIF90C = mpif90 -f90=ifort

FFLAGS = -mkl -openmp -03 -no-prec-div -fpp


However, I do have gfortran-5 ,gfortran-6 and gfortran-7 in my computer which I don not know how to set it in a way it uses gfortran-6 or 7. May you please guild me?

**Comment by cmbant** [comment]
If you look at your full make output text I'm sure you can see which compiler is being used.
