### ISSUE TITLE
chain stop when MPI communicating

### ISSUE THREAD

**Issue by bnuastro** [cmbant/CosmoMC#12]
Dear all, 
I am using cosmomc as generic sampler. I tested it for action=4 mode and it works well. 
However, the chains always run for a long time but will meet a strange error and then will never continue...

It looks like:

Chain          10  MPI communicating
TRealArrayList: object of wrong type 
 ----   ----------  ------------ ------------------------------------------------    
   mpirun has exited due to process rank 9 with PID 35466 on....

Is there any suggestions on this error? What is TRealArrayList warning?

Thank you very much!
bnu

**Comment by bnuastro** [comment]
Thank you @cmbant 
I am using gcc-6.4.1
Is there any way to modify some functions in the code to fit the gcc? Our cluster is IBM and will not use ifort...
Thanks

**Comment by cmbant** [comment]
It should work find in gcc, though it's possible a compiler bug has been introduced.

**Comment by cmbant** [comment]
Please try ad10c52d24caf89f1330b7d22e4451f00c54eff8 (though that fix was specific to resuming from checkpoint files, it sounds like the issue).

**Comment by yuanshuoastro** [comment]
@cmbant Just try the new sources on IBM cluser,
still happened:
Chain 10 MPI communicating
TRealArrayList: object of wrong type
Sorry to disturb you,
Best

**Comment by bnuastro** [comment]
Hi! @cmbant
Just try the new sources over a IBM cluster, the same errors are still happened.

**Comment by cmbant** [comment]
Make sure you have deleted all old chain .chk files, they may be corrupted.

**Comment by cmbant** [comment]
Do you chains have more than 500000 samples when this happens, and if so does it happen after thin() is called (in ObjectLists.f90)?

**Comment by bnuastro** [comment]
@cmbant  Sorry to disturb you again.
The  chain steps =       59101 for example, and I have tested over the git cloned version just now,  by testing the generic_samplers. The *.chk files are generated when I pressed Ctrl-C but restart still failed and showing
1 Reading checkpoint from chains/test2_1.chk
TObjectList: Unknown type to save

Looks different than before but still don not work.
Thank you

**Comment by cmbant** [comment]
This seems to be a version-specific gfortran compiler bug see
https://cosmocoffee.info/viewtopic.php?f=11&t=2827
