### ISSUE TITLE
hessian evaluation disabled for now

### ISSUE THREAD

**Issue by yuanshuoastro** [cmbant/CosmoMC#16]
Dear CosmoMC team,

I run the sampling with action=0 and set estimate_propose_matrix=T, but the codes stop with finding out the best-fit point without going on for the MCMC sampling.
This is quite different with the Readme's information.

Could you help me with that?

Thank you very much.

Shuo

**Comment by cmbant** [comment]
Yes, this has not been updated or supported for a while. In practice it rarely worked well enough to be very useful anyway.
