### ISSUE TITLE
Further problems with Pantheon redshifts

### ISSUE THREAD

**Issue by rameez3333** [cmbant/CosmoMC#23]
I have opened this issue with Pantheon:

https://github.com/dscolnic/Pantheon/issues/3

More details:

https://arxiv.org/abs/1905.00221v1

To me at least, these seem shocking. A lot of people include Pantheon in their cosmological fits/scans, without taking any close look at the data, primarily only because it's available through cosmoMC as a black box. I think this is dangerous.

**Comment by cmbant** [comment]
Since this concerns external data rather than directly cosmomc code itself, I am closing.

**Comment by rameez3333** [comment]
That's fine I suppose. But I'd be grateful if you also took this external data out and prevented it from shipping with your repository, so that the rest of the scientific community is not mislead by  fraudulent data. There are a large number of papers that use cosmoMC with SN1a data to make all sorts of fantastic claims that sound like science.
