### ISSUE TITLE
cliklike

### ISSUE THREAD

**Issue by gaby7646** [cmbant/CosmoMC#24]
Hi. I'm trying to install CosmoMC with Planck2015 data. And I have the following error:
`cliklike.f90(2): error #7013: This module file was not generated by any release of this compiler.   [CLIK]`
`    use clik`
`--------^`
`cliklike.f90(13): error #6457: This derived type name has not been declared.   [TCMBLIKELIHOOD]
    type, extends(TCMBLikelihood) :: ClikLikelihood
`
I was wonder if you can help me.

**Comment by joeastro5** [comment]
Hi @gaby7646 . I am getting a similar error, any chance you recall what fixed it?

**Comment by ajcosmology** [comment]
Hello, I am also facing similar problem. Can you please share what you did to resolve it?

Thanks,
Alex
