### ISSUE TITLE
New camb parameter

### ISSUE THREAD

**Issue by gaby7646** [cmbant/CosmoMC#25]
Hi, I added a new parameter in camb, which I want to vary using MH. First I put this parameter as fixed to some value, to obtain Cl's from camb, but I obtain the following error:
`forrtl: severe (174): SIGSEGV, segmentation fault occurred` 
I'm using equations_ppf.f90.

**Comment by cmbant** [comment]
If you have modified the code, this sounds like a bug with your modification not CosmoMC/CAMB, so closing.
