### ISSUE TITLE
error when running a chain with varying nnu and meffsterile

### ISSUE THREAD

**Issue by terryys** [cmbant/CosmoMC#27]
I am using the latest version of CosmoMC and CAMB. Both CosmoMC and CAMB are not modified. When I try to run a chain with varying nnu and meffsterile, the program stops with the error "CAMB error HMCode INTEGRATE, Integration timed out". The input parameter file is taken from the Planck chain base_nnu_meffsterile_plikHM_TT_lowl_lowE.

**Comment by cmbant** [comment]
I guess you have stop_on_error=T? If False, that error should just reject the point without stopping. Do you have the parameters to reproduce the issue in CAMB?

**Comment by terryys** [comment]
Yes I have stop_on_error=T. If I set it to F, the following error occurs instead:
You need to normalize realistically to use lensing.
see http://cosmocoffee.info/viewtopic.php?t=94

The problem seems to be caused by small nnu (slightly larger than 3.046) and moderate meffsterile. One set of the problematic parameters related to neutrinos (other parameters are close to the standard values):
omnuh2 = 6.033281099611884E-003
nu_mass_degeneracies = 1.01533333333333       8.191413045527840E-002
nu_mass_fractions = 0.178640662473938   0.821359337526062
In CAMB, these parameters produce the error "HMCode INTEGRATE, Integration timed out".

**Comment by cmbant** [comment]
Did you try the latest CAMB version, e.g. https://github.com/cmbant/CAMB/commit/65b3f21dad9579266552f5568beb5ce6590502ac may be relevant? If that's not it, please could you give a full test case to reproduce it with CAMB, thanks.

**Comment by cmbant** [comment]
Should be fixed in latest CAMB (let me know if you now see lots of warnings).
