### ISSUE TITLE
I have trouble with installing the latest CosmoMC, it is different between CosmoMC-Nov16 with CosmoMC-Oct19, I do not know how to install CosmoMC. Could you give me some advice?

### ISSUE THREAD

**Issue by PhyPy-Dm** [cmbant/CosmoMC#29]
I have trouble with installing the latest CosmoMC, it is different between CosmoMC-Nov16 with CosmoMC-Oct19, I do not know how to install CosmoMC. Could you give me some advice?

**Comment by cmbant** [comment]
Please read the readme and give much more detail about the exact problem if you still have one.
