### ISSUE TITLE
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor

### ISSUE THREAD

**Issue by wonyongc** [cmbant/CosmoMC#30]
Hi,
I am having issues installing CosmoMC. I am attempting to install on a fresh CentOS 8 with built-from-source gcc/gfortran 8.3.1. When running 'make,' it fails with this output about -c not being a valid option for cpp (but it definitely is a valid option).

 CosmoMC]$ make
cd ./source && make cosmomc BUILD=MPI
which: no ifort in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/dell/srvadmin/bin:/home/wonyongc/bin)
make[1]: Entering directory `/home/wonyongc/CosmoMC/source'
mkdir -p ReleaseMPI
cd ../camb/fortran && \
	make --file=Makefile_main libcamb OUTPUT_DIR=ReleaseMPI \
    FORUTILSPATH=/home/wonyongc/CosmoMC/source/../camb/forutils
make[2]: Entering directory `/home/wonyongc/CosmoMC/camb/fortran'
make -C ReleaseMPI --no-print-directory -f../Makefile FORUTILS_SRC_DIR=.. libforutils.a
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o MiscUtils.o -c ../MiscUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [MiscUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o MpiUtils.o -c ../MpiUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [MpiUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o StringUtils.o -c ../StringUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [StringUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o ArrayUtils.o -c ../ArrayUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [ArrayUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o FileUtils.o -c ../FileUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [FileUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o IniObjects.o -c ../IniObjects.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [IniObjects.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o RandUtils.o -c ../RandUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [RandUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o ObjectLists.o -c ../ObjectLists.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [ObjectLists.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o MatrixUtils.o -c ../MatrixUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [MatrixUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o RangeUtils.o -c ../RangeUtils.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [RangeUtils.o] Error 1 (ignored)
cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -DMPI -o Interpolation.o -c ../Interpolation.f90
cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[5]: [Interpolation.o] Error 1 (ignored)
ar -r libforutils.a MiscUtils.o MpiUtils.o StringUtils.o ArrayUtils.o FileUtils.o IniObjects.o RandUtils.o ObjectLists.o MatrixUtils.o RangeUtils.o Interpolation.o
ar: creating libforutils.a
ar: MiscUtils.o: No such file or directory
make[5]: *** [libforutils.a] Error 1
make[4]: *** [directories] Error 2
make[3]: *** [ReleaseMPI] Error 2
make[2]: *** [libforutils] Error 2
make[2]: Leaving directory `/home/wonyongc/CosmoMC/camb/fortran'
make[1]: *** [camb] Error 2
make[1]: Leaving directory `/home/wonyongc/CosmoMC/source'
make: *** [cosmomc] Error 2

Have you seen this issue before? Could you please advise?
Thank you.

**Comment by cmbant** [comment]
It shouldn't be using cpp but gfortran, perhaps an issue with your config or environment variables?

**Comment by wonyongc** [comment]
Hi, thanks for the response. It was an issue with openmpi. mpifort was not installed.
