### ISSUE TITLE
Compile Issue: suffix or operator invalid for "movq"

### ISSUE THREAD

**Issue by bhorowitz** [cmbant/CosmoMC#4]
Uncertain if this is an issue with the code or with my system, but I'm trying to compile the code with gfortran 6.0.0 (20151213) on my Mac (10.9.4) and am getting the following compilation error:

>gfortran -cpp -O3 -ffast-math -ffree-line-length-none -fopenmp -fmax-errors=4 -JRelease -IRelease/ -c utils.F90 -o Release/utils.o
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:11890:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:11900:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:11905:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12032:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12294:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12590:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12606:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12613:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:12748:suffix or operands invalid for `movq'
/var/folders/x9/0wlz8wlx0fs3s2xh1lbt9z4r0000gn/T//cczbEKUL.s:13083:suffix or operands invalid for `movq'
make[2]: *** [Release/utils.o] Error 1
make[1]: *** [camb] Error 2
make: *** [cosmomc] Error 2'

**Comment by cmbant** [comment]
Maybe same issue as here:
http://cosmocoffee.info/viewtopic.php?t=2653

**Comment by cmbant** [comment]
Absent and followup, now closing.
