### ISSUE TITLE
BAO DR12 CMASS

### ISSUE THREAD

**Issue by steog88** [cmbant/CosmoMC#6]
I just found some unidentified problem in the DR12 CMASS likelihood code.
With a clean installation, compiled with Intel Fortran, if you add `DEFAULT(batch3/BAO.ini)` to the `test.ini` file and you run cosmomc, you get
` Test likelihoods done, parameter point rejected (logZero or outside prior)`.
This doesn't happen if you remove the CMASS data with `bao_dataset[DR12CMASS] = `.
Does it happen only to me? Is it a known problem?
I'll try to study the details of the code next week.

**Comment by cmbant** [comment]
It seems to work OK for me with the latest DR12 update merge, could you try with that?

**Comment by steog88** [comment]
I confirm, thanks. Solved updating `source/bao.f90` and `data/sdss_DR12CMASS_bao.dataset`, adding `data/sdss_DR12CMASS_bao_dilation_qpm.dat` and `data/sdss_DR12CMASS_bao_dilation_md-patchy.dat`.
