### ISSUE TITLE
Bug in CosmologyParametrization.f90?

### ISSUE THREAD

**Issue by barunp1985** [cmbant/CosmoMC#9]
In  subroutine BK_ParamArrayToTheoryParams of  source/CosmologyParametrization.f90  are these correct initialization 

>  CMB%h=CMB%H0/100
        h2 = CMB%h**2
        CMB%Yhe=0.24
        CMB%omnu = CMB%omnuh2/h2
        CMB%omb= omegam - CMB%omnu
        CMB%ombh2 = CMB%omb*h2
        CMB%omc=0
        CMB%omch2 = CMB%omc*h2
        CMB%zre=0
        CMB%tau=0
        CMB%omdmh2 = CMB%omch2+ CMB%omnuh2
        CMB%omdm = CMB%omdmh2/h2
        CMB%omv = 1- CMB%omk - CMB%omb - CMB%omdm
        CMB%nufrac=CMB%omnuh2/CMB%omdmh2
        CMB%reserved=0
        CMB%fdm=0
        CMB%iso_cdm_correlated=0
CMB%Alens=1

Please let me know.

**Comment by cmbant** [comment]
What was the bug? (This parameterization was intended for things like supernovae where there is no sensitivity to the difference between omb and omc so they are not separate variables)

**Comment by barunp1985** [comment]
Thanks for the reply. So here omegam is all that matters, I thought 
> CMB%omb= omegam - CMB%omnu is not correct and also CMB%omc is set to zero. 
So if want to use JLA to constrain dark energy equation of state along with omegam, the above initializations are correct.
